name: Lint and Format

on:
  push:
    branches:
      - main
      - "feature/*"
  pull_request:
    branches:
      - main
      - "feature/*"

jobs:
  lint-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Bun
        uses: jarred-sumner/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Lint with Biome
        run: bun run lint

      - name: Format with Biome
        run: bun run format
